version: "3.8"

services:
  user-service:
    scale: 3
    build: ./user-service
    env_file:
      - ./user-service/.env
    environment:
      POSTGRES_DB: business_manager
      DATABASE_PORT: ${DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    volumes:
      - ./user-service:/app
      - /app/node_modules
    ports:
      - "4200-4203:4200"
    depends_on:
      database:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
