version: "3.8"

services:
  user-service:
    build: ./user-service
    container_name: userService
    env_file:
      - ./user-service/.env
    environment:
      POSTGRES_DB: business_manager
      DATABASE_URL: postgresql://postgres:postgres@database:5432/business_manager?schema=public
    volumes:
      - ./user-service:/app
      - /app/node_modules
    ports:
      - 4200:4200
    depends_on:
      database:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
